### PR TITLE
idl: Make safety comment checks fail silently when program path env is not set

### LINKED ISSUE #3042: `#[program]` macro error in rust-analyzer when LSP run with `cargo.features = "all"`
I've just upgraded to the latest version of anchor 0.30.1. Everything is fine and `anchor build` runs well. However, there's a small issue when rust-analyzer runs with `cargo.features = "all"`. This means that `idl-build` feature is switched on in the LSP.

```toml
[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
```

As a result I'm seeing this error on the `#[program]` macro. 

```
custom attribute panicked
message: Safety checks failed: Failed to get program path
```

The error originates from this variable declaration: https://github.com/coral-xyz/anchor/blob/e6d7dafe12da661a36ad1b4f3b5970e8986e5321/lang/syn/src/idl/external.rs#L20-L21

As a temporary fix I've hardcoded the env variable `ANCHOR_IDL_BUILD_PROGRAM_PATH` to point to the program path but that will stop working with multiple programs in the workspace.

### PR DESCRIPTION
**Pull request by acheroncrypto**
### Problem

IDL generation expects `ANCHOR_IDL_BUILD_PROGRAM_PATH` environment variable to be set, but if the user is using Rust Analyzer with all features enabled, they will run into a panic due the environment variable not being set as described in https://github.com/coral-xyz/anchor/issues/3042.

### Summary of changes

Make safety comment checks fail silently when the `ANCHOR_IDL_BUILD_PROGRAM_PATH` environment variable is not set.

Note that the checks still work as expected, this is only to improve an LSP related issue.

Resolves https://github.com/coral-xyz/anchor/issues/3042

### CODE REVIEW

**Comment by acheroncrypto** [comment]
Blocked by https://github.com/coral-xyz/anchor/issues/3044

**Comment by acheroncrypto** [comment]
Merging with (unrelated) CI errors because https://github.com/solana-labs/solana-program-library/issues/6897 is taking a while to get resolved.

**Comment by Abhishek7Tech** [comment]
Still the issue hasn't been resolved. @acheroncrypto

**Comment by acheroncrypto** [comment]
It has been resolved, but we don't have a release with this PR included. This is a LSP only issue, and I've shared multiple ways to fix it in https://github.com/coral-xyz/anchor/issues/3042#issuecomment-2224946150.

**Pull request merged**
