### PR TITLE
ts: improve native ESM compatibility

### PR DESCRIPTION
**Pull request by vovacodes**
This makes sure  `dist/**/*.esm.js` files are compatible with the Node flavour of ESM modules standard, which should also make it works when imported from the https://jspm.io CDN.

Additional discussion (on Discord): https://discord.com/channels/889577356681945098/891724485177245717/912681913859309609

[JSPM sandbox link](https://jspm.org/sandbox#H4sIAAAAAAAAA61ZW1PbOBR+hl+hZl9gNrZJCNcNTNLAtFBuQ8q03RdGkZVYIFuuJCeEDv99j2Q7iYtxMmxngETWOd+5Hx2L9gdfED2NKQp0yI/X2/kHxf7xOkLtkGqMSIClovqoluihs1+zG5ppTo/vIvvpt710PWOJcEiPamNGJ7GQuoaIiDSNAGLCfB0c+XTMCHXsoo5YxDTD3FEEc3rUAAFtL9WgPRD+1KJ+cBz4QOi8f3OJPtGISqyFRGehwUeXOLa7pz7T6O724hDs0bE69LxRTuo+qDh0mfD+umteBT8+fXw8udyS0/7zef+uEZDew8XFlr58fjw4v/D/vXk+HV9PewfTy6vus4bfj6Mu/jE9+34+6YIgx7E6KSJZrJHx31GNWU1CHIP6v2A3e6Bqh+iX1a3WGYsxJsKnysMRCYSErdpMTzxTMIrDw1e0nS23se+2PJ8p7VEVeizy6RPw1Oop+iAZDmkB0uKBp71sC+heDHFNERHTBcVKdJhtGr0HeEC5JxMIdkghMjymEvRS04h8FbNYVFlTQOjsuY1dd+tNoLlRbwsnHCvVw5z3Akoe3y26CLOSYEmxpj3D936pc4xVRI6ovpFCC5Nn18N3Sy3CrCKYRQGVTL/f0BxgNWGaShHf0p8Jk/SEDnHC9f+QXIK2ihqxUIoNOO2JSGmZEMjHW6oTGb1blTcRV1HHBEu8P+Ype5UgSUfvLuAF3t/bkREUS/FAiXYUlUnoDYRUQZWIEnJoek23mfY8zgZlQpTgOMJZi3M4noqkMmvK6Dvb7haYYyRc2AelIiZ0sG02VmraKY+T8XQa7vYWNO+5DQMpJmCoC528IAxaApWVBpiFR4SknabR2hnAces2ml4EcgFfeRm0l0IV0AdYUeepAj0lsP448JQkJR43JLstp9IRMxowfMdtlKFE1a60+50dCH8al0GxWpYlU549rYy9RAEpJI78KoyUAkxoAEoJgtrZr2KH7Q7ILzf/1WH97jCnUCXoy4uhWAQNW2tvFAGBeY4TCGsF3IwG4rZdajZhkiQcS8gMUdVQC3QQxh3IxkHCuO8VdlzjjKIAOY21+CN+TaEK6L7QzhIf5CS2hNJpDWq8udXYKXEH5RzmR0Yq8HKSzi44IW0g+aMi1BimaxoyDcfedhXeIp1Nz70SxQKsgur6zChscexZtXKeOUiIiePLwagKJqcBIFMpFih/VkBbYRbJSWxkW7Ph4z7vtYtwD3gKCWTlEc7AJ3ncK/BTHogsxKKEs8SPD8pRAW7u7Fah5jSQ5wfQaEzXTR+UQFWFNqMAmP05zHYBhIsJ1PuSFJ4TWUdmx+9r40J4bQsxh01GnKXnVgl1FvMlyGkdOolmvCr4b/IsZJZdFyRFYpk3MoqV6jnGj1W9x2xnuWldatZ2AAgLIFIQWv1ysXIPy7Ac+PRh8GSieIouzG9ONtpViC2hNi+l29Cbs2URPCZm/FGCPNLKsi0SwmzZgulyMenK6lfhIXWWnqILVHaWKEs2RUkMxfbYqMLJaWzHbJa3YBXhR7osneZEK2WUSswYb98aqkDnVCYirewYT+FoMeM1fdIOjWBKZdHISS903kYuobb1lArIN1xYFIWIkFehwnY2c782WStAq2I2+5D4ZsKw38HCYqvUE0p1hEmlCjmNNWfbM1+dIVbFqSdJmG8tldGo+jw0lGBSPm8CvVOWthZw3FoNaNwyvJb1pf7mTU3JlLB4ebPaoA0lV5y0V5FaXrgr3Bz9sZfaVEtzr7X+st720vs4czWX3Rii0z66hNbHKeoHLFSH+X1hiGOFYsGnQ8Y5GgqJQkumUBY1hSZMBzAFI7bAAYVmFxsYuOgTobFGvUCKkKL9g783f7sXtPdaCA7iozfjppxULpzcoJ4p3qa7n9/xFfZcOOCMyYhIoZSQbMSioxqORDQNRaJqx4vmt+dfR1wMMP8aMOWe9+/7n7vQx+6vruHn5PT+vI+OEPQNanhe82c3m6ka9toX5e74hcyrbR3dSDFmPpV19A18QrV9MpI4RC9oCI4pu/VcX19bI+YyBPW6Vyc/7i+7vc9nV6f3N7fXn267l6BSRCcW371JBpyRL3S6AcLXzIAf+dNuJC/8+OFno6/ixvP+09OJ+rjvP9G9pPX5YufqiTW/7Hz7/m8NxGzOZcHfiNozcFFAb/Z0w64JTxSMxt2Y3Um+UQsxg31tT9ja5gLaxFq7iARKxpjJjc0ZTZz5JqPKXbUx16Se4dSzklmLJR1yNgp0T4QwpIcwXh6ac5rAF+gia2svCzownwM0nmCmc6+7Q6pJcObzjVLX1mc6bVp5Mz1txGZqmtUGoNfLA7SIMoMRnLpcjFK2DHHzn0Jetb30Nr/tpf9l+A/sR5C4fRgAAA==) illustrating that the fork (with this PR applied) works:

### CODE REVIEW

**Comment by armaniferrante** [comment]
Jest tests are failing with these changes.

**Comment by vovacodes** [comment]
It seems like the issue was in combining `ts-jest` + `jest` which led to not being able to resolve `.js` extensions in the way TypeScript and NodeJS would normally do. Hopefully, fixed it by adding `ts-jest-resolver` that was created specifically to fix this issue. Also upgraded `jest` to the latest stable version which should normally work even better with ESM

**Comment by sungoki** [comment]
Hey this might break some frontends that use ESM, e.g. create react apps, since 2022 is pretty unsupported.

Is this the only way to support JSPM?

**Comment by vovacodes** [comment]
dou you refer to the tsconfig.module option? if so it should break anything as it only affects typechecking within anchor itself, but let me know if you have a repro, happy to change that back to esnext or whatever works in that case

**Pull request merged**
