### PR TITLE
Add option for jest test scaffolding 

### PR DESCRIPTION
**Pull request by kgilliam125**
I typically always manually change tests from `mocha` to `jest` when starting a new project. As `jest` is a commonly used testing framework, I added a scaffolding option, `--jest`, which scaffolds tests as jest tests instead of mocha. I kept this as a flag so that the prior behavior to create `mocha` tests by default was maintained.

How to test:
1. Build the CLI by running `make build-cli` from repo root
2. Use the newly built cli to create a project (TS and JS); `./anchor/cli/npm-package/anchor init test-ts --jest` and `./anchor/cli/npm-package/anchor init test-js --jest --javascript`
3. `cd test-ts`
4. `anchor test`  and observe success
5. `cd ../test-js`
6. `anchor test` and observe success

### CODE REVIEW

**Comment by kgilliam125** [comment]
I looked through the repo a bit to see if any docs mentioned `mocha` specifically and didn't find anything. If you think this needs a doc update let me know!

**Comment by kgilliam125** [comment]
Seems like this might close #1069 as well

**Comment by Restuta** [comment]
Awesome, finally community can get much faster tests by default! Ty @kgilliam125

**Comment by Henry-E** [comment]
It's weird, i'm not able to find the option to run the workflow on this PR.

Some people I've worked with definitely prefer `jest` to `mocha` but I'm not sure what the criteria are like for pulling the trigger on switching over from `mocha` to `jest`. I'm assuming it will mess with existing code at least a little bit?

**Comment by kgilliam125** [comment]
Thanks for taking a look @Henry-E !

> It's weird, i'm not able to find the option to run the workflow on this PR.
From what I can tell, someone with admin rights on Vercel has to authorize the workflow before it can run. I am not really sure who that is though if you aren't able to.

> I'm assuming it will mess with existing code at least a little bit?

Actually this change is backward compatible, so the existing Mocha code will continue to run just as before. The scaffolded test code for Mocha or Jest is exactly the same, save for the imports which I've updated in the new Jest sample. This is because there are no `expect` type statements in the sample code, which is where the syntactic differences between Jest/Mocha tests come in.

**Comment by Henry-E** [comment]
@armaniferrante I'll defer to you on this. In previous projects, Kevin chose Jest over Mocha. But I don't really know if this has any annoying downstream effects (plus the tests don't seem to want to run on the PR)

**Comment by Henry-E** [comment]
@kgilliam125 Just trying to push the conflict changes from my end? Is the `allow updates from maintainers` box disabled on your PR

**Comment by Henry-E** [comment]
Running into some issues when trying to test this.

```
error[E0599]: no method named `to_camel_case` found for reference `&str` in the current scope
   --> cli/src/template.rs:385:14
    |
385 |         name.to_camel_case(),
    |              ^^^^^^^^^^^^^ method not found in `&str`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following traits are implemented but not in scope; perhaps add a `use` for one of them:
    |
1   | use heck::camel::CamelCase;
    |
1   | use inflector::Inflector;
```
This compile error pops up a couple of places in `cli/src/template.rs` and it's not possible to solve via `use` for some reason, possibly missing dependencies or different versions.

**Comment by kgilliam125** [comment]
Hey @Henry-E appreciate you trying to merge in the latest. Most likely I'm going to say something with conflict resolution caused this (either in the code or just from versions updating over time), since I created 8 or so different repos with this branch's version of Anchor months back when I wrote it. I'll take a look on my end to see if I can resolve this as well.

> Is the allow updates from maintainers box disabled on your PR

Yes, just checked and this is enabled on the PR here. 

image

Maybe you are not flagged as a `maintainer` for some reason? Usually your badge will say Maintainer instead of Contributor when that is set up 

image

**Comment by kgilliam125** [comment]
@Henry-E Did some digging and this seems to be a problem introduced not too long ago in https://github.com/coral-xyz/anchor/blame/5291a7b6fff69b3249620a1130b5a210f9145aeb/cli/src/lib.rs#L475 . To use `str` calls on a `String` type you have to use `&name.to_kebab_case()` (Correct code here https://github.com/coral-xyz/anchor/blame/fb6508addff2bec4c33d428837536c44ff5e31cf/cli/src/lib.rs#L515 , note `name` is re-assigned to `project_name` in the latest version)

I'll push a fix for this to the branch here independently. Seems isolated to two lines.

**Comment by kgilliam125** [comment]
Fix pushed, should work for you now. Apparently I was wrong about String vs. &str above (maybe this was in an older version?), though I did need to `clone` to avoid unnecessary moves.

Specific to this branch, `to_camel_case` was replaced with `to_upper_camel_case` from the prior code and this branch still used the old function call. I don't have context here but thinking either from a dep update or a different type is now passed into the `template.rs` functions. Either way seems to be working on my end.

**Comment by Henry-E** [comment]
Thanks for all the hard work, I'll test this locally and hopefully merge it ASAP!

**Comment by Henry-E** [comment]
Do you know why the tests might be failing?

It seems like many of them are failing on `Workspace already initialized` or the workspace just initializes as expected. These are the errors I got locally when running `cargo test` in the root directory.

```
failures:

---- tests::test_init_using_jest_with_ts stdout ----
thread 'tests::test_init_using_jest_with_ts' panicked at 'called `Result::unwrap()` on an `Err` value: Workspace already initialized', cli/src/lib.rs:3281:10
note: panic did not contain expected string
      panic message: `"called `Result::unwrap()` on an `Err` value: Workspace already initialized"`,
 expected substring: `"Anchor init should create tests with jest using Typescript."`

---- tests::test_init_using_jest_with_js stdout ----
project initialized
note: test did not panic as expected

---- tests::test_init_invalid_ident_chars stdout ----
project-name initialized
note: test did not panic as expected

failures:
    tests::test_init_invalid_ident_chars
    tests::test_init_using_jest_with_js
    tests::test_init_using_jest_with_ts
 ```

**Comment by kgilliam125** [comment]
> Do you know why the tests might be failing?

Most likely it is a problem with the test setup for these new tests would be my guess. I'll see if I can look tonight, but may be tomorrow evening.

Will get back once I know more. Thanks again :)

**Comment by kgilliam125** [comment]
@Henry-E had a few things come up and took longer than expected. Here's the situation:

`test_init_invalid_ident_chars` was removed in prior code but I reintroduced it via merge. I removed it again.

The two tests I added, `test_init_using_jest_with_js` and `test_init_using_jest_with_ts`, were testing things which are not typically tested, namely that anchor created a folder successfully (also I had an incorrect condition should_panic). As only error conditions are tested, I removed both of these. After thinking that through, likely these kind of tests were omitted because it would create lingering folders any time someone runs `cargo test`. Both have been removed.

**Comment by stevekeol** [comment]
@kgilliam125 , I think so too. Actually, the testing framework current used is ts-mocha, which is very old version. some new features in typescript, such as "||=" operation, will throw a error.

**Comment by kgilliam125** [comment]
> @kgilliam125 , I think so too. Actually, the testing framework current used is ts-mocha, which is very old version. some new features in typescript, such as "||=" operation, will throw a error.

> @kgilliam125 , I think so too. Actually, the testing framework current used is ts-mocha, which is very old version. some new features in typescript, such as "||=" operation, will throw a error.

Hey @stevekeol my PR which added this was merged about a year ago. You should be able to scaffold out Jest tests by supplying the `--jest` flag. Admittedly I have not used it in quite a while, but I assume it still works.

**Pull request merged**
