### PR TITLE
make idl enum fields which are snake case have proper typing to camel case

### PR DESCRIPTION
**Pull request by pplisd**
solves #2374

fixes:
ts: idl enum field types properly convert from snake case to camel case

### CODE REVIEW

**Comment by Henry-E** [comment]
Looks great, would you mind to
- [ ] Add a change log
- [ ] Add a small test, just add some enums with to `tests/misc` and try to load it in a typescript test `it()` to verify that the naming is correct.

**Comment by nojob1** [comment]
for why the struct ones are fine I'm not 100% sure but I think it's just because the idl json generated for structs converts the fields to camelcase whereas the enum one does not. so they were parsing the idl basically the same  (see https://github.com/coral-xyz/anchor/blob/master/ts/packages/anchor/src/coder/borsh/idl.ts#L121) but the idl itself was just different.

I'll try to do the test i dont see the misc test but will figure something i guess.

**Comment by Henry-E** [comment]
Here's the program for misc, you could try adding some custom types maybe? I don't think you need to go all the way to actually add them to an account or load data into them since this is just to test the IDL.

program: https://github.com/coral-xyz/anchor/tree/master/tests/misc/programs/misc/src
ts test: https://github.com/coral-xyz/anchor/blob/master/tests/misc/tests/misc/misc.ts

**Comment by nojob1** [comment]
i think the test uses an idl that gets build (it's not committed) im fixing it so i can add.

**Comment by Henry-E** [comment]
We want a test though in which the IDL gets built? Please don't commit the IDL itself.

**Comment by nojob1** [comment]
idk the issue i was having was that the program had a bunch of UncheckedAccount or similar without `/// Check:` so i couldn't build the idl for misc. i just added the check and added my enum account and it worked. I wasn't trying to commit the idl

**Comment by Henry-E** [comment]
Ah right, you need to run with `anchor test --skip-lint`

**Comment by nojob1** [comment]
ah well, i guess not anymore

**Comment by Henry-E** [comment]
Great, looks good to me. Thanks for the PR!

**Comment by Henry-E** [comment]
closes: #2374

**Comment by nojob1** [comment]
oh cool thanks. 

ohh i put my changelog in the comment not in the file lmao didn't know about that. Issue was just for the types not the actual object but i guess it's close enough.

**Comment by Henry-E** [comment]
So what would be a more accurate changelog?

- ts: Fields inside enum variants weren't being converted to camelCase correctly

**Pull request merged**
