### PR TITLE
Multithreaded Client

### PR DESCRIPTION
**Pull request by cavemanloverboy**
Addresses [#2218](https://github.com/coral-xyz/anchor/issues/2218).

This introduces two changes.

1) Internally, it has the client library hold and accept some `S: Signer + Send + Sync` instead of some `dyn Signer`. This makes the `Client` (and other) types `Send` and `Sync`.
2) We change all `std::rc::Rc` to `std::sync::Arc` so that the `Client` (and other) types can be shared across threads. This allows builders to write multithreaded (async, parallel) codes that use an `anchor_client::Client`.

We also update the `client/example` to include a single and multithreaded test..

### CODE REVIEW

**Comment by Henry-E** [comment]
This seems cool for sure but looks like a major breaking change / a lot of rewriting will be needed by anyone using the new client?

**Comment by Henry-E** [comment]
I think this is good to merge just two things
- please add it as a breaking change to the changelog
- Based on some CI test errors, it looks like the zero copy test uses the client and is broken, so it also needs to be updated

Hopefully we can merge and someone of the insane people who use anchor/master to dev off of can give comments on how it affects their client experience!

**Comment by cavemanloverboy** [comment]
BTW this should no longer introduce breaking changes and all tests pass

**Comment by Henry-E** [comment]
Excellent, I will review and merge. Have you added the changelog?

**Comment by Henry-E** [comment]
I'm going to merge this before it goes on any longer but before releasing the next version of anchor it would be really helpful if you were able to write up something about how to use the new `multithreaded` option and whether anything needs to be changes about existing tests to use it. e.g. In the example test there's a slightly complicated type alias for the test function, should all multithreaded tests be written using such a pattern / type?

**Pull request merged**
