### PR TITLE
v0.13.0

### PR DESCRIPTION
**Pull request by armaniferrante**

### CODE REVIEW

**Comment by fanatid** [comment]
I'm working right now on #350 (not sure about ETA to be honest), can we wait a little for v0.13.0? :slightly_smiling_face:

**Comment by armaniferrante** [comment]
> I'm working right now on #350 (not sure about ETA to be honest), can we wait a little for v0.13.0?

These changes are mostly additive and they're needed for the verifiable build registry, so I'm inclined to not wait so that we can start onboarding projects. #350 will create a lot of breakage so we might want to batch that with other changes?

**Comment by fanatid** [comment]
@armaniferrante can you also publish [@project-serum/anchor-cli](https://www.npmjs.com/package/@project-serum/anchor-cli)?

**Comment by armaniferrante** [comment]
> @armaniferrante can you also publish [@project-serum/anchor-cli](https://www.npmjs.com/package/@project-serum/anchor-cli)?

Done. Thanks for the reminder.

**Pull request merged**
