### PR TITLE
cli: allow execute custom test command

### LINKED ISSUE #426: Allow other test framework than mocha for `anchor test`.
I do not like [mocha](https://mochajs.org/) because new global variables introduced so this requires an external runner. Instead, I usually use [tape](https://github.com/substack/tape) where tests can be run as usual js files. Another good thing for `tape` that this test framework can be easily pinned (`mocha` can be pinned too, but we need patch `PATH`).
Outside `tape` somebody else can like use [jest](https://jestjs.io/)/[ava](https://github.com/avajs/ava)/etc.

It would be nice if `anchor test` would accept test framework (through `--test-framework=xxx` for example) with `mocha` by default for backward compatibility.

I can work on this feature if you accept it.

### PR DESCRIPTION
**Pull request by fanatid**
Closes #426 

Usage example:
```bash
anchor test --cmd "npx ts-node node_modules/.bin/tape tests/*.ts"
```

### CODE REVIEW

**Comment by armaniferrante** [comment]
What do you think of adding this to the `[scripts]` section instead of the --cmd option? 

So your example turns into 

```
[scripts]
test = "npx ts-node node_modules/.bin/tape tests/*.ts"
```

Then run `anchor test`.

**Comment by fanatid** [comment]
If we add `test` field to `scripts` section which will be used by `anchor test` what does `anchor run test` should do?

**Comment by armaniferrante** [comment]
> If we add `test` field to `scripts` section which will be used by `anchor test` what does `anchor run test` should do?

Perhaps the same as `anchor test`? I'm not sure. 

I'm thinking it'll be convenient for some of the scripts probably to have special behavior similar to npm, for deploys, tests, and publishing builds (once that's ready).

**Comment by armaniferrante** [comment]
Shall we add a simple test in one of the examples?

**Comment by fanatid** [comment]
Yeah, I thought about example and where we should document the new feature. Maybe we should introduce breaking change and require `test` field in `scripts` section? i.e. move `mocha`/`ts-mocha` from cli binary to config and create it by default?

**Comment by armaniferrante** [comment]
> Yeah, I thought about example and where we should document the new feature. Maybe we should introduce breaking change and require `test` field in `scripts` section? i.e. move `mocha`/`ts-mocha` from cli binary to config and create it by default?

I don't have strong opinions. Let's file an issue and consider the breaking change separately.

**Comment by fanatid** [comment]
Updated.
- Use command from `[scripts] + test`
- On `anchor init` add default `[scripts] + test` for `mocha`/`ts-mocha`
- Instead file allow to pass custom arguments

**Review by armaniferrante — APPROVED** [review]

**Pull request merged**
