### PR TITLE
Add `setup_tests.sh` for setting up your local machine for tests

### PR DESCRIPTION
**Pull request by metaproph3t**
I was about to work on a PR to address #2586 and was trying to get my tests set up so that I could test locally. I found it pretty cumbersome to copy all of the commands from the ci files in `.github` (maybe there's a better way? in which case, this isn't necessary), so I threw them in a `justfile` in case it'd be helpful for others.

### CODE REVIEW

**Comment by acheroncrypto** [comment]
The idea is great but people shouldn't need to install another tool(`just`) only to run a few commands.

We should instead use one of the following which are already present in the repository:

- Bash script
- Node script
- `Makefile`

Related https://github.com/coral-xyz/anchor/issues/2471.

**Comment by metaproph3t** [comment]
Makes sense, will refactor to a bash script

**Comment by metaproph3t** [comment]
Ok, it's a bash script now

**Review by acheroncrypto — APPROVED** [review]
Thank you.

**Comment by baiwfg2** [comment]
I am afraid this script isn't being actively maintained. Have any changes on CI setup been reflected into this script ? 

How about directly calling the script from CI yaml so that we only need to change a single copy whenever changes happen ?

**Pull request merged**
