### PR TITLE
ts: add dex coder scaffold

### PR DESCRIPTION
**Pull request by armaniferrante**
Looking for help. Free free to take this over.

### CODE REVIEW

**Comment by harsh4786** [comment]
I'll try this!

**Comment by harsh4786** [comment]
so I'm done with the dex program part, generated the idl, kinda had some doubts on the ts side

**Comment by armaniferrante** [comment]
> so I'm done with the dex program part, generated the idl, kinda had some doubts on the ts side

Please open a pr.

**Comment by harsh4786** [comment]
done, let me know any changes, ser

**Comment by harsh4786** [comment]
That was my first pr btw

**Pull request closed without merging**
