### PR TITLE
ts: Fix browser detection

### PR DESCRIPTION
**Pull request by aximili-dev**
Relevant issue: #1232

### CODE REVIEW

**Comment by aximili-dev** [comment]
After some thought I decided it might be better to just make the variable name a bit less generic, to still allow modifying the `isBrowser` setting from the environment.

**Comment by archseer** [comment]
Relevant issue seems to link to itself

**Comment by aximili-dev** [comment]
@archseer Fixed the self link.

I closed my issue because it's basically the same as #1145, this pull request would fix that one too.

**Comment by artlogic** [comment]
I just ran up against this issue myself - any chance this could get merged?

**Pull request merged**
