### PR TITLE
add geyser_plugin_config support for anchor localnet

### PR DESCRIPTION
**Pull request by tomjohn1028**
Allows geyser plugins to be added to the test validator

### CODE REVIEW

**Comment by nickgarfield** [comment]
Yo, this is fire. Any chance we can get this into the next release?

**Comment by armaniferrante** [comment]
Yup just need to run cargo fmt on the build!

**Comment by tomjohn1028** [comment]
> Yup just need to run cargo fmt on the build!
Ran it

**Comment by Henry-E** [comment]
Happy to merge but don't have access on the PR to resolve the merge conflicts.

**Comment by tomjohn1028** [comment]
gm @Henry-E, will check out merge conflicts today and either fix or give you permissions. Still here and building :)

**Comment by tomjohn1028** [comment]
@Henry-E looks like #2150 is a copy of this code and was merged in. That's why compiling is failing. Only diff is the change log

**Comment by Henry-E** [comment]
ha, cool. Alright so if people want to see the code changes they'll have to check here instead of the changelog PR. Sounds good! https://github.com/coral-xyz/anchor/pull/2150

**Pull request merged**
