### PR TITLE
Don't use wallet object for account.createInstruction function 2112

### PR DESCRIPTION
**Pull request by Niceural**
- Deleted the wallet type check
- Replaced to get publicKey from provider

### CODE REVIEW

**Comment by armaniferrante** [comment]
Thank you!

**Comment by Niceural** [comment]
A pleasure :)

Does the code need to throw an exception if `this._provider.publicKey` is undefined?
Something similar to this:
```javascript
    // @ts-expect-error
    if (this._provider.publicKey === undefined) {
      throw new Error(
        "This function requires the Provider interface implementor to have a 'publicKey' field."
      );
    }
```

**Comment by callensm** [comment]
@Niceural might want to run typescript through the tests and rest of the TS package source to find and fix the errors that this change brings.

**Comment by Niceural** [comment]
Understood. Any ideas on what might cause the tests to fail?

**Comment by callensm** [comment]
> A pleasure :)
> 
> Does the code need to throw an exception if `this._provider.publicKey` is undefined? Something similar to this:
> 
> ```js
>     // @ts-expect-error
>     if (this._provider.publicKey === undefined) {
>       throw new Error(
>         "This function requires the Provider interface implementor to have a 'publicKey' field."
>       );
>     }
> ```

Most, if not all, of the failures I'm seeing are from Typescript type analysis failures.

`AnchorProvider#publicKey` is of type `PublicKey | undefined`. The answer to your question here is yes, there should be a defined checked.

**Comment by Niceural** [comment]
Okay thanks for your help!
Will check it out tomorrow

**Comment by Niceural** [comment]
I modified my PR and ran the tests locally, they all passed!
Let me know what to do next

**Comment by Niceural** [comment]
Does the non passing test have anything to do with this PR?

**Comment by Henry-E** [comment]
Just testing closing and reopening PR to see if it will ungrey a bunch of the buttons here.

**Comment by Henry-E** [comment]
Rebased to master and letting the tests run again

**Comment by Niceural** [comment]
thanks a lot!

**Pull request merged**
