### PR TITLE
Implement TryFromIntError conversion for AnchorError

### PR DESCRIPTION
**Pull request by CanardMandarin**
I noticed it was a bit painful to cast integers with `try_into` and `try_from` because you have to either `unwrap()` or `map_err(||)`.

What about implementing `TryFromIntError` for `Error` so we can use the `?` operator?

### CODE REVIEW

**Review by acheroncrypto — COMMENTED** [review]
Thanks, I think this would be great to have.

Before we merge, could you add a test case for this [here](https://github.com/coral-xyz/anchor/tree/128e937f4b0ad4a3044a163aed08d4b67be79a92/tests/errors)?

**Comment by CanardMandarin** [comment]
Sure! I have added a test case.

**Review by acheroncrypto — CHANGES_REQUESTED** [review]
Please also add the new error variant in TS package:

- https://github.com/coral-xyz/anchor/blob/14309ea14639b8042055e1b432bd6be24434970f/ts/packages/anchor/src/error.ts#L308
- https://github.com/coral-xyz/anchor/blob/14309ea14639b8042055e1b432bd6be24434970f/ts/packages/anchor/src/error.ts#L402

**Comment by CanardMandarin** [comment]
My bad, I should have thought about it!

**Review by acheroncrypto — CHANGES_REQUESTED** [review]
Thanks but CI has a formatting [error](https://github.com/coral-xyz/anchor/actions/runs/9043345288/job/24850883816?pr=2950#step:14:23) now. Please run `yarn lint:fix`.

Also, it might be good to include this feature in the [CHANGELOG](https://github.com/coral-xyz/anchor/blob/460a16171a715671f77ead5629391c0466366c08/CHANGELOG.md#features), otherwise it would be hard to discover.

**Comment by CanardMandarin** [comment]
Feel free to modify the changelog entry if the description is not clear.

**Review by acheroncrypto — APPROVED** [review]
Thanks!

**Pull request merged**
