### PR TITLE
Add avm to system path

### PR DESCRIPTION
**Pull request by shawazi**
Problem:

While following the documentation to install `avm`, my system was unable to locate the `avm` command. This was due to the absence of the Cargo binary directory ($HOME/.cargo/bin) in my system PATH. While this issue may stem from my own Rust installation, it might benefit users to have a reminder in the documentation about the necessity of including the Cargo binary directory in the system PATH for the successful execution of `avm install latest`.

Proposed Solution:

I suggest updating the documentation to include instructions for adding the entire Cargo binary directory to the system PATH. This will help users avoid similar issues and streamline their installation process.

Additional Concern:

`avm install latest` fails on my system, as does `avm install 0.29.0` (both with the same error):

Screenshot From 2024-09-24 05-13-41

Thank you for considering this PR!

### CODE REVIEW

**Comment by shawazi** [comment]
https://github.com/rust-lang/rust/issues/127343

I wonder if the issue with time crate's compilation is due to the linked issue, or due to some personal rust installation issue.

**Review by acheroncrypto — CHANGES_REQUESTED** [review]
This looks great, however, there is one small issue: we mention `bash`, `fish` and `zsh` below the installation page, but this change only mentions `bash` and `zsh`. For consistency, could you also mention `fish` shell between the current shells?

**Comment by shawazi** [comment]
Thank you for your feedback. I ran some tests in a fresh VM with fish, and noticed that avm is available in the same shell session without updating the fish path or reloading the shell. However, I looked up how to add cargo/bin to the system path for fish, and made some other minor syntax edits for consistency. Sorry for the wall of text, let me know if you need anything else.  

Also, the time error was present there as well for attempting to use `avm install latest`. 

Should I make a separate PR and link to the solution in https://github.com/coral-xyz/anchor/issues/3131#issuecomment-2264178262 from the official documentation for getting started?

**Review by acheroncrypto — APPROVED** [review]
Thank you for contributing!

> Should I make a separate PR and link to the solution in https://github.com/coral-xyz/anchor/issues/3131#issuecomment-2264178262 from the official documentation for getting started? I forgot to take a picture, but the same issue occurred with the time crate in the VM fish avm installation that required the 3131 solution.

Making changes to published crates is not really a great solution, especially when there are easier solutions such as running:

```sh
rustup default 1.79.0 && avm install <VERSION>
```

I don't think it's necessary to mention this in documentation because the problem is fixed already. We just need a new release (https://github.com/coral-xyz/anchor/pull/3259), but it's currently on hold because of something external.

**Pull request merged**
