### PR TITLE
Update rust to v1.62

### PR DESCRIPTION
**Pull request by Henry-E**
- Just updating from 1.56 to 1.65.
- Have a horrible feeling this introduces some new clippy lint that complains about the `Result<>` size being too large. For now will need to find a way to disable that particular lint globally since it shows up so many places?

### CODE REVIEW

**Comment by Henry-E** [comment]
Looks like it has to be 1.64 because that's what the github CI supports at the moment. 🤷  At least we don't have to deal with the clippy lint about large result types.

**Comment by Aursen** [comment]
You can disable the lint for error

**Comment by Henry-E** [comment]
Now we're all the way back down to v1.62 because that's what the current solana cli version supports. Going to keep this in mind next time I try to update the rust version 😂

**Comment by Henry-E** [comment]
Also finally passing, time to merge.

**Pull request merged**
