### PR TITLE
updated, outdated methods of basic-0,1,2,3

### PR DESCRIPTION
**Pull request by vpin09**
It had outdated  implementation of rpc methods in basic-0,1,2,3. I have updated the  outdated rpc methods to follow the new standard of anchor framework.

### CODE REVIEW

**Comment by stegaBOB** [comment]
@Henry-E can you approve this run? Looks like a solid PR to me :).

**Comment by Henry-E** [comment]
I can't figure out how to get it to rerun the tests. There's something weird about the workflow that looks different to the usual stuff.

**Comment by Henry-E** [comment]
Reverted, unless the original author comes back someone will have to fork this fork and make the necessary updates to get the tests passing.

**Comment by metaproph3t** [comment]
> Reverted, unless the original author comes back someone will have to fork this fork and make the necessary updates to get the tests passing.

Done in [2238](https://github.com/coral-xyz/anchor/pull/2238)

**Pull request merged**
