### PR TITLE
ts: Add data type to clients in `AccountNamespace`

### LINKED ISSUE #1312: AccountNamespace and AccountClient types are too general
The current implementation effectively merges the fields from all of the account types together:

https://github.com/project-serum/anchor/blob/71f9c02c9171c0edb8ba31c7bdf47374efc3d8c3/ts/src/program/namespace/account.ts#L68-L78

I believe it should be using the key M when setting up the AccountClient, probably something along these lines:

```ts
export type AccountNamespace<IDL extends Idl = Idl> = {
  [M in keyof AllAccountsMap<IDL>]: AccountClient<IDL, AllAccountsMap<IDL>[M]>;
};
```

I'd be happy to make this change if it makes sense to do so.

### PR DESCRIPTION
**Pull request by hsheth2**
Closes https://github.com/project-serum/anchor/issues/1312.

### CODE REVIEW

**Comment by hsheth2** [comment]
@armaniferrante - the test failures seem unrelated?

e.g. a PR from a couple days ago failed with the same error in `tests/misc` https://github.com/project-serum/anchor/runs/4921584185?check_suite_focus=true

**Comment by fanatid** [comment]
I restarted CI.

**Comment by hsheth2** [comment]
@fanatid - I doubt that will help, since it seems like there's a pre-existing issue with the `tests/misc` test. 

Other PRs seem to be failing because of the same issue. For instance, a PR that changes the book is also failing with the exact same error message: https://github.com/project-serum/anchor/actions/runs/1731458790.

**Comment by armaniferrante** [comment]
Build failures is now fixed and was due to https://github.com/solana-labs/solana-program-library/issues/2791.

**Comment by armaniferrante** [comment]
Please merge master to get CI to build.

**Comment by dietmerc** [comment]
👌

**Comment by imaai** [comment]
@armaniferrante @hsheth2 Why was that reverted?

**Pull request merged**
