### PR TITLE
Add support for idl enum tuples, enchance types

### PR DESCRIPTION
**Pull request by devDesu**
- Recursive types decoding
- Correct enum types decoding
- IdlEvents type

### CODE REVIEW

**Comment by devDesu** [comment]
@armaniferrante please take a look at the PR

**Comment by devDesu** [comment]
Ping @armaniferrante

**Comment by skulltech** [comment]
This would be very useful!! +1

**Comment by ngundotra** [comment]
This is very helpful! This would also make the `spl_governance` Anchor IDL work (which depends on enum variants with tuple data)

**Comment by devDesu** [comment]
Ping @ChewingGlass @Henry-E @armaniferrante

**Comment by Henry-E** [comment]
I don't feel fully qualified to review the PR but it looks safe enough.
It's adding some extra functionality to the IDL type stuff and it has
tests. I'll try to take a deeper look at it tomorrow.

**Comment by devDesu** [comment]
ping @Henry-E @stegaBOB @ChewingGlass

**Comment by armaniferrante** [comment]
Thanks @devDesu for your persitence!

**Pull request merged**
