### PR TITLE
Simple Versioned Transaction Support

### PR DESCRIPTION
**Pull request by Henry-E**
Just making some minimal changes to the Anchor ts package and provider / wallet API to support versioned transactions. 

Essentially `provider`and the wallet interface will support `Transaction | VersionedTransaction` inputs. 

Eventually it would be nice to get rid of `Transaction` entirely and make the whole interface cleaner and more aligned with the new `VersionedTransaction` approach in the solana web3 package but for now we're just going for minimal changes.

### CODE REVIEW

**Comment by Henry-E** [comment]
There must be something up with the cache because these tests are all passing locally now.

**Comment by GuidoDipietro** [comment]
Hey there. Wonder if this PR is going to be fixed and merged soon? Just to have a clearer idea of the status of this feature

**Comment by Henry-E** [comment]
As you can see by the commit history this is actively being worked on and should be ready to merge pretty soon.

**Comment by Henry-E** [comment]
Let's just yolo merge this because CI seems out of date or using an old cache maybe. I can't reproduce the error it's getting.

**Pull request merged**
