### PR TITLE
Make zero copy safe by default, add `account(zero_copy(unsafe))` feature.

### PR DESCRIPTION
**Pull request by ckamm**
The default account(zero_copy) feature unsafe impls the bytemuck traits

The new one derives it instead, which runs desired sanity checks like "struct has no padding".

### CODE REVIEW

**Comment by Aursen** [comment]
Why not do it by default? It would be interesting to remove all the unsafe code

**Comment by ckamm** [comment]
> Why not do it by default? It would be interesting to remove all the unsafe code

That would break backwards compatibility. It'd be fine with me, but is a choice I'd leave up to the anchor maintainers.

**Comment by Henry-E** [comment]
Having talked to armani and robert chen about this a while ago, it's probably best to make this the default and anyone that wants to can manually implement their own unsafe types.

**Comment by ckamm** [comment]
@Henry-E I've covered some of your suggestions. The existing zero_copy docs already referenced bytemuck::Pod safety restrictions, so I didn't know what to add there.
- I didn't know where to add the note about deprecated `unsafe_bytemuck_derives`
- Fixing the test looked tricky, I made it pass by using `unsafe_bytemuck` for now
Could you take care of the rest?

**Comment by Henry-E** [comment]
Sure, thanks very much for all that. I'll look into finishing the rest soon.

**Comment by ckamm** [comment]
@Henry-E Use `bytemuck` with the `features = ["min_const_generics"]` feature -- newer rust versions allow generically implementing Pod for static arrays of all sizes.

You can't use `Vec<>` with zero-copy. Vec is just a struct of a few pointers and all the actual data ends up on the heap.

**Comment by Henry-E** [comment]
@ckamm that solved it, thanks very much! 

Another thing that I find kind of annoying but don't really know what to do about is how even though we use a reference to anchor's privately exported bytemuck crate `derive(anchor_lang::__private::bytemuck::Pod)`, once these macros are expanded they switch to using the local crate's bytemuck, e.g. `::bytemuck::Pod`. I'm not sure if it's possible to do anything about this.

**Comment by Henry-E** [comment]
No worries, I think I'll do one more review of this tomorrow morning and then I think it's good to merge.

**Pull request merged**
