### PR TITLE
ci: add git diff for checking lock file changes

### PR DESCRIPTION
**Pull request by fanatid**
Moved from https://github.com/project-serum/anchor/pull/1653

### CODE REVIEW

**Comment by paul-schaaf** [comment]
just to make sure I understand correctly, is the reason for adding this that `cargo build` will sometimes adjust the lock file and if that happens we want that committed before the CI so the lock file is not adjusted in the CI?

**Comment by fanatid** [comment]
Yes, purpose of this changes to validate that dependencies on CI (rust/js) will be same as on developer computer.

**Comment by paul-schaaf** [comment]
is this ready for review?

**Comment by fanatid** [comment]
Yes, it's ready. One thing I do not like that submodules like `action-house`/`stake`/`swap` change `Cargo.lock` so we need checkout it. But we can fix it in the future.

**Comment by paul-schaaf** [comment]
Ideally we should use `cargo build-bpf --locked` (`--locked` doesn't exist on `build-bpf` though) right?

**Comment by fanatid** [comment]
We can pass `--locked` through `--`:
```bash
$ cargo build-bpf -- --locked
BPF SDK: /home/kirill/.local/share/solana/install/releases/1.9.13/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release --locked
```

While I think that would be good to add `--locked` (`--frozen-lockfile` for `yarn`) have `git diff` at the end still will be useful.
Are you agree with adding `--locked`/`--frozen-lockfile`? (if yes, I'll change PR)

**Comment by paul-schaaf** [comment]
oh thats right nice! Lets do it then.

keeping `git diff` sounds good.

**Comment by fanatid** [comment]
Updated.

**Pull request merged**
