### PR TITLE
ts: Fix sendAndConfirm getTransaction version

### LINKED ISSUE #2921: Bug: provider.sendAndConfirm() maxSupportedTransactionVersion
Got the following error after calling `provider.sendAndConfirm(VersionedTransaction)`:

> SolanaJSONRPCError: failed to get transaction: Transaction version (0) is not supported by the requesting client. Please try the request again with the following configuration parameter: "maxSupportedTransactionVersion": 0

`sendAndConfirm()` doesn't set `maxSupportedTransactionVersion` in `getTransaction()`:
https://github.com/coral-xyz/anchor/blob/fefa69519fb9b875cac72469b8d5021f8c2d90a5/ts/packages/anchor/src/provider.ts#L177-L179

It should probably be like this:
```typescript
const failedTx = await this.connection.getTransaction(txSig, {
  commitment: "confirmed",
  maxSupportedTransactionVersion: isVersionedTransaction(tx) ? 0 : undefined
});
```

### PR DESCRIPTION
**Pull request by czkz**
Resolves #2921

### CODE REVIEW

**Review by acheroncrypto — COMMENTED** [review]
Thanks!

Before we merge, could you note this fix in the [CHANGELOG](https://github.com/coral-xyz/anchor/blob/827c986618358c177a50c22ff8eb08bae6943784/CHANGELOG.md#fixes)?

**Comment by czkz** [comment]
Found and fixed the same bug in `sendAll` as well.
Updated changelog.

**Review by acheroncrypto — APPROVED** [review]
Thank you!

**Comment by 0xdal** [comment]
we need a new release for this

**Pull request merged**
