### PR TITLE
ts: fix methods namespace typing loss and deprecate non-methods namespaces

### LINKED ISSUE #1434: TS: Builder API types are cascaded as any after .method call.
```ts
const result = await program.methods
      .makeConnection(to)
      .accounts({
        from,
        systemProgram: anchor.web3.SystemProgram.programId,
      })
      .signers([fromWallet.payer])
      .rpc();
```

.accounts is cascaded as any, breaking completion.

Screen Shot 2022-02-10 at 22 12 33

### LINKED ISSUE #1442: ts: Mark all program namespaces (except for methods) as deprecated
A simple doc comment should do the trick.

### PR DESCRIPTION
**Pull request by callensm**
resolves #1434 
resolves #1442

### CODE REVIEW

**Comment by Beardev118** [comment]
Which method can use instead of deprecated rpc?

**Comment by callensm** [comment]
the `program.methods` namespace is now the preferred namespace to use.

**Comment by Beardev118** [comment]
Okay, thank you

**Comment by gabRiel-bit20** [comment]
Will be worth add some documentation pointing to `methods` when marking `rpc`, `instruction` deprecated.

**Pull request merged**
