### PR TITLE
Respect absent logs on simulation

### PR DESCRIPTION
**Pull request by rogaldh**
I'd consider using the `safe` operator to cover absent logs cases.

Having such a response will fail the method execution:
```jsonc
{
  jsonrpc: '2.0',
  error: {
    code: -32003,
    message: 'Transaction signature verification failure',
    data: undefined
  },
  id: 'e23c1fad-e3ca-47bf-ad0f-11a5bd4b49c2'
}
```

### CODE REVIEW

**Comment by acheroncrypto** [comment]
It wouldn't hurt to merge this but is `data` ever `undefined`?

**Comment by rogaldh** [comment]
It's the case when we receive a response without a data field; `32003`, for ex.
https://github.com/coral-xyz/anchor/blob/ceb220bf99dbb5cdc4ec72b50c1e716e8b91273a/ts/packages/anchor/src/utils/rpc.ts#L193-L194

`data` will appear after applying `SimulatedTransactionResponseStruct` on the `unsafeRes`.

Actually, the response (`unsafeRes`) causing troubles looks like [that](https://github.com/solana-labs/solana/blob/master/rpc/src/rpc.rs#L5965-L5972). 
```jsonc
{
  jsonrpc: '2.0',
  error: {
    code: -32003,
    message: 'Transaction signature verification failure'
  },
  id: '1'
}
```
I assume that affects any error with just the `code` and `message` properties.

**Comment by acheroncrypto** [comment]
> It's the case when we receive a response without a data field; `32003`, for ex.
> 
> https://github.com/coral-xyz/anchor/blob/ceb220bf99dbb5cdc4ec72b50c1e716e8b91273a/ts/packages/anchor/src/utils/rpc.ts#L193-L194
> 
> `data` will appear after applying `SimulatedTransactionResponseStruct` on the `unsafeRes`.
> 
> Actually, the response (`unsafeRes`) causing troubles looks like [that](https://github.com/solana-labs/solana/blob/master/rpc/src/rpc.rs#L5965-L5972).
> 
> ```js
> {
>   jsonrpc: '2.0',
>   error: {
>     code: -32003,
>     message: 'Transaction signature verification failure'
>   },
>   id: '1'
> }
> ```
> 
> I assume that affects any error with just the `code` and `message` properties.

Yes, thank you but that case is already handled:

https://github.com/coral-xyz/anchor/blob/b8eda6980c895d709b2859ef456e0bc83675f903/ts/packages/anchor/src/utils/rpc.ts#L197

The check will only pass if `data` property exists.

**Comment by rogaldh** [comment]
It exists, tbh.
`create` adds the key to the object, like I've said before:
```
{
  res: {
    jsonrpc: '2.0',
    error: {
      code: -32003,
      message: 'Transaction signature verification failure',
      data: undefined
    },
    id: '94192407-d2ca-470f-8f22-a7fa0c9121fc'
  }
}

**Comment by acheroncrypto** [comment]
Thanks, this wouldn't hurt in any case. CI is failing(not due to your changes) because it's outdated, could you update this branch to master?

**Review by acheroncrypto — APPROVED** [review]

**Pull request merged**
